# Generated by Django 6.0.8 on 2026-08-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na listagem')),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'English')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=100)),
                ('short_desc', models.TextField()),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('solution_details', models.JSONField(blank=True, default=dict, help_text='Mapa opcional, ex: {"apis": {"label": "APIs & Segurança", "text": "..."}}')),
                ('impact', models.JSONField(blank=True, default=list)),
                ('disclaimer', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('link_label', models.CharField(blank=True, max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='projects.project')),
            ],
            options={
                'ordering': ['project__order'],
                'unique_together': {('project', 'language')},
            },
        ),
    ]
