# Generated by Django 6.0.8 on 2026-08-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'English')], max_length=5)),
                ('chapter', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário')], max_length=20)),
                ('stack', models.JSONField(blank=True, default=list, help_text='Lista de tecnologias, ex: ["Python", "Django"]')),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('not_needed', models.JSONField(blank=True, default=list)),
                ('reading_time', models.PositiveIntegerField(help_text='Minutos de leitura')),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, help_text='Data prevista, para capítulos ainda não publicados', null=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('body', models.TextField(blank=True, help_text='Conteúdo em Markdown')),
            ],
            options={
                'ordering': ['chapter'],
                'unique_together': {('slug', 'language')},
            },
        ),
        migrations.CreateModel(
            name='GuideFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('helpful', 'Ajudou'), ('missing', 'Faltou algo')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='guides.guide')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
